name: ghbuild


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  call_build: 
    #uses: WorldHealthOrganization/smart-base/.github/workflows/ghbuild.yml@main
    uses: joofio/smart-base/.github/workflows/ghbuild.yml@main
    with:
      tx: http://tx.hl7europe.eu/r5
